# Generated by Django 4.2.1 on 2023-05-09 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Field must contain only alphabetic characters', regex='[a-zA-Z\\s]+$')])),
                ('categoryPic', models.ImageField(blank=True, null=True, upload_to='static', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Field must contain at least one alphabetic characters', regex='[a-zA-Z]+')])),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productPic', models.ImageField(upload_to='static')),
                ('avgRating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('quantity', models.IntegerField(default=0)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.category')),
            ],
        ),
    ]
