# Generated by Django 4.2 on 2023-05-02 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(10)])),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
