# Generated by Django 4.2 on 2023-05-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
