# Generated by Django 3.2.18 on 2023-05-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('street_no', models.CharField(max_length=10)),
                ('government', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=10)),
                ('apartment_no', models.CharField(blank=True, max_length=10, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
