# Generated by Django 3.2.18 on 2023-05-04 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryPic',
            field=models.ImageField(blank=True, null=True, upload_to='static', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Field must contain only alphabetic characters', regex='^[a-zA-Z]+$')]),
        ),
    ]
