# Generated by Django 3.2.18 on 2023-05-04 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Field must contain only alphabetic characters', regex='[a-zA-Z\\s]+$')]),
        ),
    ]
