# Generated by Django 3.2.18 on 2023-05-05 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Field must contain at least one alphabetic characters', regex='[a-zA-Z]+')]),
        ),
    ]
